# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_model',
        ),
    ]
